### ISSUE TITLE
Wazuh/Management/CDB lists dont have support for double quotes

### ISSUE THREAD

**Issue by ThepoisonedApple** [wazuh/wazuh-dashboard-plugins#5064]
Wazuh-manager have support for double quotes in cdb lists.
https://github.com/wazuh/wazuh/issues/1500
But gui dont have support for it.
When i wrote 
```
 "my:key":my:value
"my:key":"my:value"
 my_key:"my:value"
 my_key:my_value
```
in cdb list.Gui cant process it.
![image](https://user-images.githubusercontent.com/37880676/210503158-2be52f3e-28c4-4438-8145-970d0f4230bd.png)
When you try to save without change anything gives an error.
```
Error: Could not upload CDB list file (1800) - Bad format in CDB list {path} 
    at Function.returnErrorInstance (https://10.10.10.10/1/bundles/plugin/wazuh/wazuh.plugin.js:1:117304)
    at Function._callee2$ (https://10.10.10.10/1/bundles/plugin/wazuh/wazuh.plugin.js:1:115518)
    at tryCatch (https://10.10.10.10/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1:341529)
    at Generator.invoke [as _invoke] (https://10.10.10.10/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1:345493)
    at forEach.prototype.<computed> [as next] (https://10.10.10.10/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1:342654)
    at asyncGeneratorStep (https://10.10.10.10/1/bundles/plugin/wazuh/wazuh.plugin.js:1:109554)
    at _next (https://10.10.10.10/1/bundles/plugin/wazuh/wazuh.plugin.js:1:109865)
```

**Comment by AlexRuiz7** [comment]
Thank you very much for the report @ThepoisonedApple 

We'll investigate this issue ASAP.

**Comment by Desvelao** [comment]
It was fixed in https://github.com/wazuh/wazuh-dashboard-plugins/issues/7154
