### ISSUE TITLE
Cannot edit CDB Lists that are in a subdirectory

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#5842]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | 00 | Chrome, Firefox, Safari, etc |

**Description**
Hi team,
It is not possible to modify CDB Lists that are in a subdirectory, such as the AWS default CDB lists.

Clicking on the pencil icon of a CDB list inside a subdirectory and then just pressing the `Save` button (_with or without any modification_), causes an API error.

```
Error: Could not upload CDB list file (1805) - File with the same name already exists in a subdirectory. 
    at Function.returnErrorInstance (https://192.168.1.188/45001/bundles/plugin/wazuh/wazuh.plugin.js:1:172681)
    at Function._callee2$ (https://192.168.1.188/45001/bundles/plugin/wazuh/wazuh.plugin.js:1:170901)
    at tryCatch (https://192.168.1.188/45001/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:760622)
    at Generator.invoke [as _invoke] (https://192.168.1.188/45001/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:764638)
    at Generator.next (https://192.168.1.188/45001/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:761817)
    at asyncGeneratorStep (https://192.168.1.188/45001/bundles/plugin/wazuh/wazuh.plugin.js:1:164530)
    at _next (https://192.168.1.188/45001/bundles/plugin/wazuh/wazuh.plugin.js:1:164841)
```

Related Issue:
#5176 

**Steps to reproduce**
1. Navigate to Management -> CDB Lists

**Screenshots**

![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/28f5aac3-880a-4b81-997b-da53d3866c35)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/85d11ae9-7870-4665-9d88-5826e4a06b20)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by gdiazlo** [comment]
Blocked by https://github.com/wazuh/wazuh/issues/19419

**Comment by Tostti** [comment]
Tested with the developement branch mentioned in https://github.com/wazuh/wazuh/issues/19419, it works without any change in the Wazuh Dashboard plugin. We have to wait until it's merged to test again and confirm that it works.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/b0a8a4c9-733a-4e2d-a001-9e326aff07a2)

**Comment by Tostti** [comment]
As notified in https://github.com/wazuh/wazuh/issues/19419#issuecomment-1790594044, this will not be applied now.
