### ISSUE TITLE
Unexpected error in console in AWS module

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-dashboard-plugins#6022]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.7.0 | 01 | Edge |

**Description**

When browsing the AWS module we detected an unexpected error message.

```
Uncaught TypeError: Cannot read properties of null (reading 'top_left')
    at scaleBounds (tileMap.plugin.js:7:19724)
    at CoordinateMapsVisualization.updateGeohashAgg (tileMap.plugin.js:7:21470)
    at CoordinateMapsVisualization._callee3$ (tileMap.plugin.js:7:25659)
    at tryCatch (customImportMapDashboards.plugin.js:13:786910)
    at Generator.invoke [as _invoke] (customImportMapDashboards.plugin.js:13:790926)
    at Generator.next (customImportMapDashboards.plugin.js:13:788105)
    at asyncGeneratorStep (tileMap.plugin.js:7:15924)
    at _next (tileMap.plugin.js:7:16235)
    at tileMap.plugin.js:7:16385
    at new Promise (<anonymous>)
```

**Steps to reproduce**
1. Navigate to 'Agents'
2. Select an agent
3. Select "More..." from the menu
4. Select 'Amazon AWS'
5. Change to 'Events'
6. Change to 'Dashboard' again

**Expected Result**
1. Should not show this error

**Actual Result**
1. The error appears consistently in the console

**Comment by gdiazlo** [comment]
This is a known issue with the maps component. It also affects the upstream platform.
