### ISSUE TITLE
[WazuhError]: Wazuh API error: ERR_BAD_REQUEST - Permission denied: Resource type: *:*

### ISSUE THREAD

**Issue by himanashu42078** [wazuh/wazuh-dashboard-plugins#6134]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| v4.6.0 | 1 | Chrome |

**Description**
Hi Team,
I have installed the Wazuh v4.6.0 and followed the below document to give a user permission to read and manage a group of agents.
[https://documentation.wazuh.com/current/user-manual/user-administration/rbac.html#use-case-give-a-user-permissions-to-read-and-manage-a-group-of-agents](https://github.com/wazuh/wazuh-dashboard-plugins/pull/url)

After that, if I log in with the user I'm able to read the data but getting the below error. 

```
Wazuh API error: ERR_BAD_REQUEST - Permission denied: Resource type: *:*
AxiosError: Wazuh API error: ERR_BAD_REQUEST - Permission denied: Resource type: *:*
    at settle (https://192.168.56.19/46003/bundles/plugin/wazuh/wazuh.plugin.js:8:20234)
    at XMLHttpRequest.onloadend (https://192.168.56.19/46003/bundles/plugin/wazuh/wazuh.plugin.js:8:25708)
```

**Steps to reproduce**
To reproduce the issue we can follow the steps mentioned in the below document.
[https://documentation.wazuh.com/current/user-manual/user-administration/rbac.html#use-case-give-a-user-permissions-to-read-and-manage-a-group-of-agents](https://github.com/wazuh/wazuh-dashboard-plugins/pull/url)

**Expected Result**
While we use the dashboard it should not show any warning/error.
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/73813999/09b7d2eb-b111-4e23-ab5a-4255ea7a3f40)

**Actual Result**
Getting the below error while using the dashboard.
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/73813999/c6310952-4aca-4002-a4c0-4bd373ee2b2f)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/73813999/9d1481c4-50c9-49a7-be89-810f34e64cc3)

**Additional context**

From the browser dev tools --> network, it is shown below api is failing with a 500 error.
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/73813999/d8edce6e-4263-461d-be8e-ad65e34714e3)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/73813999/04573082-6c12-424c-8b44-f87674c9779c)

Please let me know if I'm missing anything or if there is any other way also to achieve this.

Thanks in advance!!

**Comment by himanashu42078** [comment]
created another
