### ISSUE TITLE
`TypeError` and `Could not fetch data for this agent` messages found after using the API Console

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-dashboard-plugins#6211]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.7.0 (OVA) | 03 | Brave |

**Description**

After making some requests in the WUI using the API Console tool, an error was obtained when "navigating back" indicating a TypeError

https://192.168.57.19/app/wazuh#/agents?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_a=(columns:!(_source),filters:!(),index:'wazuh-alerts-*',interval:auto,query:(language:kuery,query:''),sort:!())

When trying to reproduce it, this other behavior was found: `Could not fetch data for this agent.`

**Preconditions**
1. -

**Steps to reproduce**
1. Navigate to `Wazuh -> Agents -> Most active agent`
2. Click on `Wazuh -> Tools -> API Console`
3. Type `GET /agents?_` and click on Run
4. A message stating `Could not fetch data for this agent` appeared

**Expected Result**
1. The most active agent page should be shown

**Actual Result**
1. Message of not agent data found or TypeError

**Screenshots**

https://192.168.57.19/app/wazuh#/agents?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_a=(columns:!(_source),filters:!(),index:'wazuh-alerts-*',interval:auto,query:(language:kuery,query:''),sort:!())

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/14913942/6e1c105a-7a63-480f-a6f3-66c6885d4a64)

https://192.168.57.19/app/wazuh#/agents?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&tabView=panels&tab=welcome

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/14913942/844dc33b-999f-469b-aba5-da889c014ae0)

**Additional context**

I have not been able to reproduce the TypeError, but I think it is produced for some wrong API Console input

Maybe related: https://github.com/wazuh/wazuh-dashboard-plugins/issues/4104 (note: this issue does not report an error in red)
Maybe related: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5332

- Console error when the `Could not fetch...` message appears

```
Uncaught (in promise) Error: TypeError: Cannot read properties of null (reading 'id')
    at AgentsController._callee7$ (wazuh.chunk.10.js:1:9006961)
    at tryCatch (customImportMapDashboards.plugin.js:13:786910)
    at Generator.invoke [as _invoke] (customImportMapDashboards.plugin.js:13:790926)
    at Generator.next (customImportMapDashboards.plugin.js:13:788105)
    at agents_asyncGeneratorStep (wazuh.chunk.10.js:1:8987106)
    at _next (wazuh.chunk.10.js:1:8987423)
    at wazuh.chunk.10.js:1:8987587
    at new Promise (<anonymous>)
    at AgentsController.<anonymous> (wazuh.chunk.10.js:1:8987335)
    at AgentsController.getAgent (wazuh.chunk.10.js:1:9007099)
```

- Console error when the `TypeError` message appears

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at _callee4$ (reportsDashboards.plugin.js:24:201073)
    at tryCatch (reportsDashboards.plugin.js:24:180012)
    at Generator.invoke [as _invoke] (reportsDashboards.plugin.js:24:183963)
    at Generator.next (reportsDashboards.plugin.js:24:181151)
    at asyncGeneratorStep (reportsDashboards.plugin.js:1:73707)
    at _next (reportsDashboards.plugin.js:1:74018)
    at reportsDashboards.plugin.js:1:74168
    at new Promise (<anonymous>)
    at reportsDashboards.plugin.js:1:73930
    at checkURLParams (reportsDashboards.plugin.js:24:202215)
```

**Comment by Tostti** [comment]
PR successfully merged
