### ISSUE TITLE
Warning related to Moment JS Date() - Value not in a recognized format

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-dashboard-plugins#6212]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 01 | Edge Version 119.0.2151.97 (Official build) (arm64) - macOS |

**Description**

The following message appears in the Dev Console (Demo environment):

```console
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Dec 7, 2023 @ 15:11:35.000, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://demo.wazuh.info/48001/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:21:51777)
    at https://demo.wazuh.info/48001/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:21:72021
    at https://demo.wazuh.info/48001/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:21:72072
    at _t (https://demo.wazuh.info/48001/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:21:72384)
    at At (https://demo.wazuh.info/48001/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:21:72645)
    at wt (https://demo.wazuh.info/48001/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:21:72727)
    at r (https://demo.wazuh.info/48001/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:21:48694)
    at formatUIDate (https://demo.wazuh.info/48001/bundles/plugin/wazuh/wazuh.chunk.10.js:1:2199053)
    at agents_info_AgentInfo.render (https://demo.wazuh.info/48001/bundles/plugin/wazuh/wazuh.chunk.10.js:1:3693696)
    at Ia (https://demo.wazuh.info/48001/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:441:69877)
```

**Preconditions**
1. Logout if you have an active session
2. Login

**Steps to reproduce**
1. Navigate to Endpoints Summary (Agents preview)
3. Select an agent

**Comment by gdiazlo** [comment]
Realted to:
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6220
