### ISSUE TITLE
getPatternList error with read-only users in a particular tenant

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7100]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | xyzw | Chrome, Firefox, Safari, etc |

**Description**
Some requests to the endpoint `api/saved_objects/_find?type=index-pattern&fields=title&fields=fields&per_page=9999` fail with the error:

```
no permissions for [indices:data/read/search] and User [name=testuser, backend_roles=[], requestedTenant=null]: security_exception: [security_exception] Reason: no permissions for [indices:data/read/search] and User [name=testuser, backend_roles=[], requestedTenant=null]
```

This happens to users that have read-only permissions to a specific tenant, like in the following configuration:

<details>
<summary>Details</summary>

In `opensearch_dashboards.yml` enable multi-tenancy:

`opensearch_security.multitenancy.enabled: true`

Create a new read-only user with permissions in a particular tenant

![image](https://github.com/user-attachments/assets/8a2c7d61-79c3-480e-afaf-acc6fcceab9b)

![image](https://github.com/user-attachments/assets/43a9558c-6d9f-446b-9096-609f1c0f699b)

Load a dashboard (or any view with visualizations) and check the browser dev-tools for security exceptions:

![image](https://github.com/user-attachments/assets/5a06af47-79b8-4a72-b001-f8244a4a3309)

![image](https://github.com/user-attachments/assets/9493a6d3-a500-4798-ad6f-a63a8c74c776)

</details>

**Comment by Desvelao** [comment]
I could replicate the problem.

I noticed the error related to getting the index pattern list through an API request, returns the http code 403 while the `global` tenant was selected despite the user has no permission on this tenant. I switch the tenant to the configured that the user should have permissions and I got the same response in the realted API requests.

Then, I refreshed the page and the related API request had `200` http code.

I am researching where the tenant information is saved. I guess this could be encoded in the `security_authenticat` cookie, but I could not find how this is encoded and what information is included.

**Comment by guidomodarelli** [comment]
> I am researching where the tenant information is saved. I guess this could be encoded in the `security_authentication` cookie, but I could not find how this is encoded and what information is included.

`security_authentication`:
```js
{
  username: 'user-ro',
  credentials: {
    authHeaderValue: 'Basic dXNlci1ybzomVXFZSiZCJkhGM0pkWkt6NzR5c3hjJFdmUiRmc1BjOA=='
  },
  authType: 'basicauth',
  isAnonymousAuth: false,
  expiryTime: 1732046561826,
  tenant: 'test_tenant'
}
```

```
Issue in fetching data sources: StatusCodeError: Authorization Exception
    at respond (/home/node/kbn/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/home/node/kbn/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/home/node/kbn/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/home/node/kbn/node_modules/lodash/lodash.js:4991:19)
    at IncomingMessage.emit (node:events:529:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  status: 403,
  displayName: 'AuthorizationException',
  path: '/_plugins/_query/_datasources',
  query: {},
  body: '{\n' +
    '  "status": 403,\n' +
    '  "error": {\n' +
    '    "type": "OpenSearchSecurityException",\n' +
    '    "reason": "There was internal problem at backend",\n' +
    '    "details": "no permissions for [cluster:admin/opensearch/ql/datasources/read] and User [name\\u003duser-ro, backend_roles\\u003d[], requestedTenant\\u003dtest_tenant]"\n' +
    '  }\n' +
    '}',
  statusCode: 403,
  response: '{\n' +
    '  "status": 403,\n' +
    '  "error": {\n' +
    '    "type": "OpenSearchSecurityException",\n' +
    '    "reason": "There was internal problem at backend",\n' +
    '    "details": "no permissions for [cluster:admin/opensearch/ql/datasources/read] and User [name\\u003duser-ro, backend_roles\\u003d[], requestedTenant\\u003dtest_tenant]"\n' +
    '  }\n' +
    '}',
  toString: [Function (anonymous)],
  toJSON: [Function (anonymous)]
}
```

```
server    log   [19:02:42.442] [error][data][opensearch] [security_exception]: no permissions for [indices:data/read/search] and User [name=user-ro, backend_roles=[], requestedTenant=null]
```

**Comment by Desvelao** [comment]
I found the client to do the request to get the saved objects of the index patterns has data about the selected tenant.

- See: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.16.0/src/core/server/saved_objects/service/lib/repository_opensearch_client.ts#L60

The security tenant seems to be stored in:
```ts
client[Object.getOwnPropertySymbols(client)[11]].headers.securitytenant
```

I assume the problem could be related to the client that does the API request to the Wazuh indexer has no information about the selected tenant for some reason. Maybe the `security_authentication` cookie has no information about the selected tenant and causes this creates a client without tenant information. This was not checked because the error randomly happens.

**Comment by JuanGarriuz** [comment]
### Test on 4.10.2

![Image](https://github.com/user-attachments/assets/6a45196a-29f6-4a53-b8a6-f85ae4eb774e)

`no permissions for [indices:data/read/search] and User [name=readonly, backend_roles=[], requestedTenant=]: security_exception: [security_exception] Reason: no permissions for [indices:data/read/search] and User [name=readonly, backend_roles=[], requestedTenant=]`

**Comment by asteriscos** [comment]
Since this issue happens sporadically and doesn't block the use of the application.
